### PR TITLE
Update aerospace.rb

### PR DESCRIPTION
**Pull request by LaurentFough**
Add Environment option to allow Upgrade/ Install sans quarantine

### CODE REVIEW

**Comment by nikitabobko** [comment]
1. How did you verify the fix? (please describe your steps)
2. Where did you find `env_set`? I can't find it in the Cask Cookbook https://docs.brew.sh/Cask-Cookbook

**Comment by nikitabobko** [comment]
Reference: https://github.com/nikitabobko/AeroSpace/issues/140

**Comment by nikitabobko** [comment]
> Where did you find env_set?

Ok, I see you call the method right away. This fix doesn't sound right to me. You are changing env variables (mutating the global state) during package configuration (which is supposed to be a declarative description of the package)

**Comment by nikitabobko** [comment]
Besides, does it affect other packages during `brew upgrade`? Most probably -- yes, and it's not a good thing

**Comment by LaurentFough** [comment]
> Besides, does it affect other packages during `brew upgrade`? Most probably -- yes, and it's not a good thing

@nikitabobko:

1) `env_set`; is just a locally declared function to set the env.
The env can be set out in the open, but I like to segregate actions in code.

2) No, the env set only affects the state of the calling formula/cask.
It doesn't affect global or current shell/env/session state.
—

I may need to test again though.
My research indicates that this was an issue  previously with Homebrew. Not respecting ENV vars.

- REF: [New brew upgrade/reinstall --cask does not honour --no-quarantine #9139](https://github.com/Homebrew/brew/issues/9139)

It appears to have been fixed upstream, but there may have been a regression.
- REF/ FIX: [UX fix - Properly allow quarantine in 'upgrade' #10398](https://github.com/Homebrew/brew/pull/10398)

* I'll dig deeper

**Comment by nikitabobko** [comment]
Close this PR in favor of https://github.com/nikitabobko/homebrew-tap/commit/8f99ddca416ea54a1f27f0371a43a6d0860f7c25

**Pull request closed without merging**
